project:
  type: website

website:
  title: 'TG repository: smoking cessation'
  back-to-top-navigation: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: 'Home'
      - section: "Helper functions and prep"
        contents:
          - helper-variance-decomposition.qmd
          - helper-corr-age-at-baseline.qmd
          - helper-corr-cig-at-baseline.qmd
          - helper-corr-spy.qmd
          - helper-wilcoxon-tests.qmd
          - helper-lmm.qmd
          - helper-immuneSMK.qmd
          - metabolome-anno.qmd
          - selbal.qmd
          - mefisto.qmd
      - section: "Figures"
        contents:
          - fig1-overview.qmd
          - fig2-clin-imm.qmd
          - fig3-epi.qmd
          - fig4-metab.qmd
          - fig5-microb-revised.qmd
          - fig6-integration.qmd
      - section: "Tables"
        contents:
          - st1.qmd
          - st2.qmd
          - st3.qmd
          - st4.qmd
          - st5.qmd
          - st6.qmd
          - st7.qmd
          - st9.qmd
          - st10.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



